# Optional config that can be passed to a matcher object.
preprocess:
  gamma: 2.0 # 2.0
  sharpness: null # null
  scale: 1.6 # 1.6
extractor:
  max_num_keypoints: null # null
matcher:
  filter_threshold: 0.5 # 0.5